<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WhatsAppErrorCode;

class WhatsAppErrorCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $codes = [
            // Authorization errors
            [
                'code' => '0',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Authentication Failure',
                'details' => 'We were unable to authenticate the app user.',
                'possible_reasons' => 'Typically this means the included access token has expired, been invalidated, or the app user has changed a setting to prevent all apps from accessing their data.',
                'possible_solutions' => 'Generate a new system user access token in Meta Business Manager and update the channel credentials.',
                'client_explanation' => 'Your WhatsApp connection token has expired or is no longer valid.',
                'client_solution' => 'Please reconnect your WhatsApp number or update your connection token.',
                'http_status_code' => 401,
            ],
            [
                'code' => '3',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Capability or Permissions Issue',
                'details' => 'Capability or permissions issue.',
                'possible_reasons' => 'The access token does not have the required WhatsApp Business management permissions for the requested endpoint.',
                'possible_solutions' => 'Use the Meta Access Token Debugger to verify that your app has been granted whatsapp_business_management and whatsapp_business_messaging permissions.',
                'client_explanation' => 'Your account does not have permission to perform this specific action.',
                'client_solution' => 'Check your WhatsApp account permissions or ask an administrator to grant required access.',
                'http_status_code' => 403,
            ],
            [
                'code' => '10',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Permission Denied or Removed',
                'details' => 'Permission is either not granted or has been removed.',
                'possible_reasons' => 'App lacks required permissions, account is not eligible for the endpoint, or the phone number used to set public encryption keys is not allowlisted.',
                'possible_solutions' => 'Check the Access Token Debugger, verify eligibility requirements, and ensure your WABA is fully onboarded.',
                'client_explanation' => 'This action is not permitted for your current WhatsApp account setup.',
                'client_solution' => 'Make sure your business account is verified and has granted all required permissions.',
                'http_status_code' => 403,
            ],
            [
                'code' => '190',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Access Token Expired',
                'details' => 'Your access token has expired.',
                'possible_reasons' => 'The access token lifetime has ended or was invalidated by a password reset or permission change on Meta.',
                'possible_solutions' => 'Generate a permanent System User Token in Meta Business Manager.',
                'client_explanation' => 'Your WhatsApp connection has expired.',
                'client_solution' => 'Please reconnect your WhatsApp channel in Settings to renew your connection.',
                'http_status_code' => 401,
            ],
            [
                'code' => '200',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Missing Access Token',
                'details' => 'No access token was provided. Provide valid app ID.',
                'possible_reasons' => 'Request was sent without an Authorization Bearer header.',
                'possible_solutions' => 'Ensure the request includes a valid Bearer access token in the Authorization header.',
                'client_explanation' => 'WhatsApp credentials are missing for this request.',
                'client_solution' => 'Verify that your channel credentials are properly configured.',
                'http_status_code' => 400,
            ],
            [
                'code' => '200-299',
                'subcode' => null,
                'category' => 'Authorization',
                'title' => 'Permission Not Granted',
                'details' => 'Permission is either not granted or has been removed.',
                'possible_reasons' => 'App has not been granted specific WhatsApp Cloud API permissions.',
                'possible_solutions' => 'Use the Access Token Debugger to inspect granted permissions and grant missing scopes.',
                'client_explanation' => 'Your account does not have sufficient permission for this feature.',
                'client_solution' => 'Review your app permissions in Meta Business Manager.',
                'http_status_code' => 403,
            ],

            // Integrity errors
            [
                'code' => '368',
                'subcode' => null,
                'category' => 'Integrity',
                'title' => 'Account Restricted or Disabled',
                'details' => 'The WhatsApp Business Account associated with the app has been restricted or disabled for violating a platform policy.',
                'possible_reasons' => 'Platform policy violation enforcement, spam complaints, or terms violation.',
                'possible_solutions' => 'Review Meta Business Support Home to inspect active policy violations and request a review.',
                'client_explanation' => 'Your WhatsApp Business account is temporarily restricted by WhatsApp.',
                'client_solution' => 'Open Meta Business Suite to check for any policy alerts and request an account review.',
                'http_status_code' => 403,
            ],
            [
                'code' => '130497',
                'subcode' => null,
                'category' => 'Integrity',
                'title' => 'Country Messaging Restriction',
                'details' => 'The WhatsApp Business Account is restricted from messaging to users in certain countries.',
                'possible_reasons' => 'Business category restrictions for international messaging.',
                'possible_solutions' => 'Consult WhatsApp Business Messaging Policy for allowed countries in your business category.',
                'client_explanation' => 'You cannot send messages to this specific country due to WhatsApp policy restrictions.',
                'client_solution' => 'Check your allowed messaging countries in WhatsApp Business settings.',
                'http_status_code' => 403,
            ],
            [
                'code' => '131031',
                'subcode' => null,
                'category' => 'Integrity',
                'title' => 'Account Locked or PIN Mismatch',
                'details' => 'The WhatsApp Business Account associated with the app has been restricted or disabled for violating a platform policy, or we were unable to verify data included in the request (e.g, the two-step pin included in the request is incorrect).',
                'possible_reasons' => 'Account lock due to policy violation or incorrect two-step verification PIN during registration.',
                'possible_solutions' => 'Verify two-step verification PIN and check the Health Status API in Meta Business Manager.',
                'client_explanation' => 'Your WhatsApp account details could not be verified or the security PIN is incorrect.',
                'client_solution' => 'Double-check your 6-digit security PIN and account status in Meta Business Manager.',
                'http_status_code' => 403,
            ],

            // Calling errors
            [
                'code' => '138015',
                'subcode' => '2593145',
                'category' => 'Calling',
                'title' => 'Calling Cannot Be Enabled',
                'details' => 'Calling APIs cannot be enabled for this phone number.',
                'possible_reasons' => 'Meta requires a messaging limit tier of at least 1,000 (Tier 1K) messages per 24h before Calling APIs can be enabled. New WhatsApp numbers typically start at Tier 250 and developer test numbers (+1 555...) do not support VoIP calling.',
                'possible_solutions' => 'Scale active messaging volume to reach Messaging Tier 1K. Ensure the phone number is a live, verified business number with an approved display name and active billing.',
                'client_explanation' => 'Your WhatsApp number is brand new or on the initial starter plan. WhatsApp automatically unlocks voice & video calling once your business builds regular customer messaging activity.',
                'client_solution' => 'Keep chatting and sending messages to your customers. WhatsApp will automatically enable calling as your messaging volume scales up.',
                'http_status_code' => 400,
            ],

            // Template creation errors
            [
                'code' => '2388039',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Template Status Locked',
                'details' => 'The status for this message template can\'t be changed. You can only delete or add templates.',
                'possible_reasons' => 'Attempted to edit a template whose status cannot be changed (e.g. still in review or daily edit limit reached).',
                'possible_solutions' => 'Wait until the template review completes (APPROVED/REJECTED) before editing, or create a new template.',
                'client_explanation' => 'This message template cannot be edited right now because WhatsApp is still reviewing it.',
                'client_solution' => 'Wait until WhatsApp approves or rejects the template before making changes.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388040',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Character Limit Exceeded',
                'details' => 'A field in your template has exceeded the maximum character limit allowed.',
                'possible_reasons' => 'Header, body, or footer text exceeds Meta character limits.',
                'possible_solutions' => 'Shorten template text to comply with maximum character constraints.',
                'client_explanation' => 'Your template message is too long.',
                'client_solution' => 'Shorten your text to fit within WhatsApp character limits.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388047',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Header Format Incorrect',
                'details' => 'Your message header contains invalid formatting.',
                'possible_reasons' => 'Header formatting syntax error or unsupported media format.',
                'possible_solutions' => 'Correct header formatting according to Meta template guidelines.',
                'client_explanation' => 'The header in your template has formatting errors.',
                'client_solution' => 'Check your template header text or media file format and try again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388072',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Body Format Incorrect',
                'details' => 'Your message body contains invalid formatting.',
                'possible_reasons' => 'Invalid variable placeholders or unbalanced brackets in message body.',
                'possible_solutions' => 'Ensure parameters follow sequential format {{1}}, {{2}} with proper spacing.',
                'client_explanation' => 'The message text format is invalid (such as misplaced {{1}} placeholders).',
                'client_solution' => 'Make sure variable placeholders are numbered sequentially: {{1}}, {{2}}, {{3}}.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388073',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Footer Format Incorrect',
                'details' => 'Your message footer contains invalid formatting.',
                'possible_reasons' => 'Footer text contains variables or exceeds character limits.',
                'possible_solutions' => 'Footers must be static plain text without variable placeholders.',
                'client_explanation' => 'The template footer text is invalid.',
                'client_solution' => 'Keep the footer simple and avoid using variables or links in it.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388293',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Parameter Words Ratio Exceeded',
                'details' => 'This template has too many variables for its length. Reduce the number of variables or increase the message length.',
                'possible_reasons' => 'Too many parameters relative to static surrounding text.',
                'possible_solutions' => 'Add more static explanatory text or decrease the number of variable placeholders.',
                'client_explanation' => 'This template has too many blank variables for the amount of text.',
                'client_solution' => 'Add more regular text around your variables so WhatsApp can understand the context.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388299',
                'subcode' => null,
                'category' => 'Template creation',
                'title' => 'Leading or Trailing Parameters Disallowed',
                'details' => 'Variables cannot be at the start or end of the template.',
                'possible_reasons' => 'Template body starts with {{1}} or ends with a parameter.',
                'possible_solutions' => 'Place static words before the first variable and after the last variable.',
                'client_explanation' => 'A template cannot start or end directly with a variable placeholder.',
                'client_solution' => 'Add regular words before the first variable and after the last variable.',
                'http_status_code' => 400,
            ],

            // Send template errors
            [
                'code' => '2388019',
                'subcode' => null,
                'category' => 'Send template',
                'title' => 'Message Template Limit Exceeded',
                'details' => 'You have exceeded the maximum number of message templates you can have for this WhatsApp business account.',
                'possible_reasons' => 'WABA has reached the maximum cap of 250 message templates.',
                'possible_solutions' => 'Delete obsolete or rejected templates in WhatsApp Manager before creating new ones.',
                'client_explanation' => 'You have reached the maximum limit of 250 message templates.',
                'client_solution' => 'Delete old or unused templates in your template manager before creating new ones.',
                'http_status_code' => 400,
            ],

            // Phone migration errors
            [
                'code' => '2388012',
                'subcode' => null,
                'category' => 'Phone migration',
                'title' => 'Phone Number Already Exists',
                'details' => 'The phone number you are trying to migrate is already present in your WhatsApp account.',
                'possible_reasons' => 'Phone number already registered on the destination WABA.',
                'possible_solutions' => 'Use a phone number that is not already attached to this WhatsApp account.',
                'client_explanation' => 'This phone number is already connected to your WhatsApp account.',
                'client_solution' => 'Select a different phone number or manage your existing connected number.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388091',
                'subcode' => null,
                'category' => 'Phone migration',
                'title' => 'Not Eligible for Registration Code',
                'details' => 'This phone number isn\'t eligible to receive/verify a registration code since it is not being migrated.',
                'possible_reasons' => 'Phone ownership verification API not applicable for non-migrated number.',
                'possible_solutions' => 'Register and verify the number directly through Embedded Signup or Two-Step PIN API.',
                'client_explanation' => 'This phone number cannot receive a verification code in this mode.',
                'client_solution' => 'Please connect this number using the standard WhatsApp connection window.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388093',
                'subcode' => null,
                'category' => 'Phone migration',
                'title' => 'Not Eligible for Registration Code',
                'details' => 'This phone number isn\'t eligible to receive/verify a registration code since it is not being migrated.',
                'possible_reasons' => 'Phone ownership verification API not applicable for non-migrated number.',
                'possible_solutions' => 'Register and verify the number directly through Embedded Signup.',
                'client_explanation' => 'This phone number cannot be verified in this step.',
                'client_solution' => 'Connect your number via the official WhatsApp Business setup modal.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2388103',
                'subcode' => null,
                'category' => 'Phone migration',
                'title' => 'Cannot Migrate Phone Number',
                'details' => 'Webhooks not set / Display name pending / Payment account missing / Business Manager mismatch.',
                'possible_reasons' => 'Destination WABA missing webhooks, display name not approved, credit line missing, or business verification pending.',
                'possible_solutions' => 'Ensure destination WABA is verified, display name is APPROVED, and an active payment method is configured.',
                'client_explanation' => 'This phone number cannot be moved because your WhatsApp account setup is incomplete.',
                'client_solution' => 'Make sure your business display name is approved and a payment method is attached in Meta Business Suite.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2494100',
                'subcode' => null,
                'category' => 'Phone migration',
                'title' => 'Account in Maintenance Mode',
                'details' => 'The business phone number is in maintenance mode.',
                'possible_reasons' => 'Meta infrastructure undergoing maintenance or upgrade.',
                'possible_solutions' => 'Try again in a few minutes.',
                'client_explanation' => 'WhatsApp servers are currently undergoing brief routine maintenance.',
                'client_solution' => 'Please try again in 5 to 10 minutes.',
                'http_status_code' => 503,
            ],

            // Template insights errors
            [
                'code' => '200005',
                'subcode' => null,
                'category' => 'Template insights',
                'title' => 'Template Insights Unavailable',
                'details' => 'Template insights are not available yet for this WhatsApp Business account.',
                'possible_reasons' => 'Account does not meet minimum analytics volume criteria.',
                'possible_solutions' => 'Insights will activate as template message volume increases.',
                'client_explanation' => 'Analytics for message templates are not available yet for your account.',
                'client_solution' => 'Analytics will appear once your account starts sending more template messages.',
                'http_status_code' => 400,
            ],
            [
                'code' => '200006',
                'subcode' => null,
                'category' => 'Template insights',
                'title' => 'Cannot Disable Template Insights',
                'details' => 'Invalid operation. Template Insights cannot be disabled once enabled.',
                'possible_reasons' => 'Attempted to disable an irreversible analytics setting.',
                'possible_solutions' => 'Template insights cannot be disabled once active.',
                'client_explanation' => 'Template analytics are permanently enabled on your account.',
                'client_solution' => 'No action needed; analytics remain active.',
                'http_status_code' => 400,
            ],
            [
                'code' => '200007',
                'subcode' => null,
                'category' => 'Template insights',
                'title' => 'Template Insights Not Enabled',
                'details' => 'Template Insights have not been enabled for this WhatsApp Business Account.',
                'possible_reasons' => 'Analytics tracking not activated on WABA.',
                'possible_solutions' => 'Enable template analytics in Meta Business Manager.',
                'client_explanation' => 'Template statistics are currently turned off.',
                'client_solution' => 'Enable template analytics in your WhatsApp Business Manager settings.',
                'http_status_code' => 400,
            ],

            // Synchronization errors
            [
                'code' => '2593107',
                'subcode' => null,
                'category' => 'Synchronization',
                'title' => 'Sync Limit Exceeded',
                'details' => 'You have exceeded the maximum number of times to call the synchronization api for this phone number.',
                'possible_reasons' => 'History/contacts sync API called more than the 1-time limit.',
                'possible_solutions' => 'Offboard the business customer and re-onboard them if complete resync is required.',
                'client_explanation' => 'You have already synchronized your account contacts history.',
                'client_solution' => 'No further sync is needed as your contacts are already up to date.',
                'http_status_code' => 400,
            ],
            [
                'code' => '2593108',
                'subcode' => null,
                'category' => 'Synchronization',
                'title' => 'Sync Window Expired',
                'details' => 'Synchronization request can only be made within 24 hours of onboarding.',
                'possible_reasons' => 'More than 24 hours elapsed since customer onboarding.',
                'possible_solutions' => 'Sync must be initiated within the first 24 hours of onboarding.',
                'client_explanation' => 'The initial 24-hour setup window for importing historical chats has passed.',
                'client_solution' => 'New messages will sync automatically in real-time going forward.',
                'http_status_code' => 400,
            ],

            // Throttling errors
            [
                'code' => '4',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Application Rate Limit Hit',
                'details' => 'The app has reached its API call rate limit.',
                'possible_reasons' => 'Too many API queries made by the application in a short window.',
                'possible_solutions' => 'Reduce API query frequency, implement request caching, and retry after backoff.',
                'client_explanation' => 'Too many requests were sent in a very short time.',
                'client_solution' => 'Please wait a moment before trying again.',
                'http_status_code' => 429,
            ],
            [
                'code' => '80007',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'WABA Rate Limit Reached',
                'details' => 'The WhatsApp Business Account has reached its rate limit.',
                'possible_reasons' => 'WABA account-level API call volume exceeded.',
                'possible_solutions' => 'Spread out API requests across time using background queues.',
                'client_explanation' => 'Your WhatsApp account is temporarily busy handling many requests.',
                'client_solution' => 'Wait 1 to 2 minutes and retry your action.',
                'http_status_code' => 429,
            ],
            [
                'code' => '130429',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Throughput Limit Reached',
                'details' => 'Cloud API message throughput has been reached.',
                'possible_reasons' => 'Message sending rate exceeded the channel throughput cap (e.g., 80 MPS or 250 MPS).',
                'possible_solutions' => 'Queue outgoing messages and throttle batch dispatch rate.',
                'client_explanation' => 'Messages are being sent faster than your WhatsApp speed tier allows.',
                'client_solution' => 'The system will automatically queue and deliver your messages at the proper pace.',
                'http_status_code' => 429,
            ],
            [
                'code' => '131048',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Spam Restriction on Number',
                'details' => 'Message failed to send because there are restrictions on how many messages can be sent from this phone number. This may be because too many previous messages were blocked or flagged as spam.',
                'possible_reasons' => 'Low phone number quality rating due to high customer block and report rates.',
                'possible_solutions' => 'Check quality rating in WhatsApp Manager, pause low-quality templates, and message only opted-in users.',
                'client_explanation' => 'Your message limit was temporarily reduced because several customers reported or blocked previous messages.',
                'client_solution' => 'Ensure you only message customers who have explicitly opted in, and send high-quality, relevant updates.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131056',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Recipient Message Rate Exceeded',
                'details' => 'Too many messages sent from the sender phone number to the same recipient phone number in a short period of time.',
                'possible_reasons' => 'Sending multiple messages rapidly to the same recipient.',
                'possible_solutions' => 'Wait a few moments before sending additional messages to this specific contact.',
                'client_explanation' => 'Too many messages were sent to this same customer in a few seconds.',
                'client_solution' => 'Wait a few seconds before sending another message to this contact.',
                'http_status_code' => 429,
            ],
            [
                'code' => '133016',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Registration Attempt Limit',
                'details' => 'Registration or Deregistration failed because there were too many attempts for this phone number in a short period of time.',
                'possible_reasons' => 'Repeated registration/deregistration requests.',
                'possible_solutions' => 'Wait until the temporary block duration expires before retrying registration.',
                'client_explanation' => 'Too many connection attempts were made on this phone number.',
                'client_solution' => 'Please wait 15 minutes before attempting to connect this number again.',
                'http_status_code' => 429,
            ],
            [
                'code' => '131064',
                'subcode' => null,
                'category' => 'Throttling',
                'title' => 'Messaging Limit Classification Penalty',
                'details' => 'Message failed to send because this account has reached its messaging limit due to template classification violations.',
                'possible_reasons' => 'Misclassifying marketing content as utility or authentication templates.',
                'possible_solutions' => 'Correct template categories in WhatsApp Manager; restrictions lift after enforcement period.',
                'client_explanation' => 'Your sending limit was lowered because promotional messages were sent using non-marketing templates.',
                'client_solution' => 'Make sure promotional content is categorized under Marketing templates.',
                'http_status_code' => 400,
            ],

            // Other errors
            [
                'code' => '1',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Server Error or Invalid Request',
                'details' => 'Invalid request or possible server error.',
                'possible_reasons' => 'Meta API internal failure or malformed request payload.',
                'possible_solutions' => 'Check WhatsApp Business Platform Status page (metastatus.com) and verify request syntax.',
                'client_explanation' => 'WhatsApp servers experienced a temporary glitch.',
                'client_solution' => 'Please wait a moment and retry.',
                'http_status_code' => 500,
            ],
            [
                'code' => '2',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Service Temporary Downtime',
                'details' => 'Temporary due to downtime or due to being overloaded.',
                'possible_reasons' => 'Meta servers temporarily overloaded.',
                'possible_solutions' => 'Retry request after exponential backoff.',
                'client_explanation' => 'WhatsApp services are temporarily overloaded.',
                'client_solution' => 'Please retry in a few moments.',
                'http_status_code' => 503,
            ],
            [
                'code' => '33',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Phone Number Deleted',
                'details' => 'The business phone number has been deleted.',
                'possible_reasons' => 'Phone number was deleted in Meta Business Manager.',
                'possible_solutions' => 'Verify phone number ID and reconnect active channel.',
                'client_explanation' => 'This phone number was removed from your Meta account.',
                'client_solution' => 'Reconnect your active phone number in Channels.',
                'http_status_code' => 404,
            ],
            [
                'code' => '100',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Invalid Request Parameter',
                'details' => 'The request included one or more unsupported or misspelled parameters.',
                'possible_reasons' => 'Misspelled field name, invalid parameter value, or unsupported option.',
                'possible_solutions' => 'Review endpoint documentation and verify parameter spelling and data types.',
                'client_explanation' => 'The request contains invalid or unsupported information.',
                'client_solution' => 'Check the information you entered and try again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '130403',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'User Blocked By Business',
                'details' => 'Unable to deliver the message. This business has blocked the end user on WhatsApp.',
                'possible_reasons' => 'Recipient is present on the WABA blocklist.',
                'possible_solutions' => 'Unblock the WhatsApp user before attempting to message them.',
                'client_explanation' => 'You cannot message this person because your business has blocked them on WhatsApp.',
                'client_solution' => 'Unblock this customer first if you wish to contact them.',
                'http_status_code' => 400,
            ],
            [
                'code' => '130472',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Message Filtered by Experiment',
                'details' => 'Message was not sent as part of an experiment.',
                'possible_reasons' => 'Meta Marketing Message Experiment holdout group.',
                'possible_solutions' => 'Check Marketing Message Experiment settings in WhatsApp Manager.',
                'client_explanation' => 'This message was held back by WhatsApp marketing experiment testing.',
                'client_solution' => 'You can resend the message later or check experiment settings in WhatsApp Manager.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131000',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Unknown Message Error',
                'details' => 'Message failed to send due to an unknown error.',
                'possible_reasons' => 'Temporary internal processing error on Meta Cloud API.',
                'possible_solutions' => 'Retry sending message; contact Meta Direct Support if problem persists.',
                'client_explanation' => 'Message could not be sent due to a temporary WhatsApp connection issue.',
                'client_solution' => 'Please try sending your message again.',
                'http_status_code' => 500,
            ],
            [
                'code' => '131005',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Permission Missing',
                'details' => 'Permission is either not granted or has been removed.',
                'possible_reasons' => 'Missing messaging permission on access token.',
                'possible_solutions' => 'Verify access token permissions in Meta Token Debugger.',
                'client_explanation' => 'Your WhatsApp account does not have messaging permission enabled.',
                'client_solution' => 'Make sure your account has full messaging permissions granted.',
                'http_status_code' => 403,
            ],
            [
                'code' => '131008',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Missing Required Parameter',
                'details' => 'The request is missing a required parameter.',
                'possible_reasons' => 'A mandatory parameter was omitted in the request body.',
                'possible_solutions' => 'Check endpoint reference and provide all required fields.',
                'client_explanation' => 'Some required information is missing from your request.',
                'client_solution' => 'Fill in all required fields and try again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131009',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Parameter Value Invalid',
                'details' => 'One or more parameter values are invalid.',
                'possible_reasons' => 'Parameter value format does not match expected schema.',
                'possible_solutions' => 'Check parameter value formats and allowed enum options in documentation.',
                'client_explanation' => 'One of the values provided is invalid or formatted incorrectly.',
                'client_solution' => 'Review the entered details and correct any formatting mistakes.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131016',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Service Unavailable',
                'details' => 'A service is temporarily unavailable.',
                'possible_reasons' => 'Temporary outage on Meta Cloud API service.',
                'possible_solutions' => 'Check metastatus.com and retry after brief delay.',
                'client_explanation' => 'WhatsApp Cloud servers are temporarily offline.',
                'client_solution' => 'Please try again in a few minutes.',
                'http_status_code' => 503,
            ],
            [
                'code' => '131021',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Sender and Recipient Identical',
                'details' => 'Sender and recipient phone number is the same.',
                'possible_reasons' => 'Attempted to send a message to the business\'s own phone number.',
                'possible_solutions' => 'Send messages to customer phone numbers different from sender number.',
                'client_explanation' => 'You cannot send a WhatsApp message to your own business number.',
                'client_solution' => 'Please choose a customer phone number to receive this message.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131026',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Undeliverable Message',
                'details' => 'Unable to deliver message. Reasons: recipient not on WhatsApp, terms not accepted, or outdated app.',
                'possible_reasons' => 'Recipient does not have an active WhatsApp account, has not accepted latest Privacy Policy, or uses outdated app version.',
                'possible_solutions' => 'Verify customer phone number or ask recipient to update WhatsApp and accept terms.',
                'client_explanation' => 'The message could not be delivered. The contact might not have WhatsApp installed, needs to update their app, or hasn\'t accepted WhatsApp\'s latest terms.',
                'client_solution' => 'Confirm that the customer phone number is active on WhatsApp.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131037',
                'subcode' => null,
                'category' => 'Other',
                'title' => '555 Number Display Name Missing',
                'details' => 'The 555 business phone number used to send the request does not have an approved display name.',
                'possible_reasons' => 'Sandbox 555 number display name not approved.',
                'possible_solutions' => 'Set an approved display name for the 555 test number in WhatsApp Manager.',
                'client_explanation' => 'This test phone number needs an approved business display name.',
                'client_solution' => 'Set an approved display name in Meta WhatsApp Manager.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131042',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Payment Account Error',
                'details' => 'There was an error related to your payment method.',
                'possible_reasons' => 'Payment account missing, credit line over limit, currency/timezone unset, or WABA suspended.',
                'possible_solutions' => 'Attach a valid credit card or credit line in Meta Business Manager and check billing status.',
                'client_explanation' => 'There is a billing or payment method issue on your WhatsApp account.',
                'client_solution' => 'Check and update your payment card or credit line in Meta Business Suite.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131045',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Registration Error',
                'details' => 'Message failed to send due to a phone number registration error.',
                'possible_reasons' => 'Phone number registration incomplete on Cloud API.',
                'possible_solutions' => 'Complete phone number registration with 6-digit PIN before sending messages.',
                'client_explanation' => 'This phone number registration is not completely finished on WhatsApp.',
                'client_solution' => 'Complete the phone number setup in Channels.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131047',
                'subcode' => null,
                'category' => 'Other',
                'title' => '24-Hour Window Expired',
                'details' => 'More than 24 hours have passed since the recipient last replied to the sender number.',
                'possible_reasons' => 'WhatsApp 24-hour customer service session expired; regular free-form text messages cannot be sent.',
                'possible_solutions' => 'Send an approved Message Template to reopen the 24-hour conversation window.',
                'client_explanation' => 'More than 24 hours have passed since this customer last messaged your business.',
                'client_solution' => 'Send an approved WhatsApp Template message to reopen the chat.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131049',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Ecosystem Engagement Limit',
                'details' => 'This message was not delivered to maintain healthy ecosystem engagement.',
                'possible_reasons' => 'Meta per-user marketing template limit exceeded.',
                'possible_solutions' => 'Wait at least 24 hours before resending marketing template messages to this user.',
                'client_explanation' => 'This customer has already received multiple marketing messages recently.',
                'client_solution' => 'Wait at least 24 hours before sending another promotional message to this contact.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131050',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'User Opted Out of Marketing',
                'details' => 'Unable to deliver the message. This recipient has chosen to stop receiving marketing messages on WhatsApp from your business.',
                'possible_reasons' => 'User tapped "Stop Promotions" in their WhatsApp chat.',
                'possible_solutions' => 'Do not retry sending marketing messages to this contact.',
                'client_explanation' => 'This customer has opted out and asked to stop receiving promotional messages.',
                'client_solution' => 'Do not send promotional messages to this customer; you can only reply to their customer service questions.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131051',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Unsupported Message Type',
                'details' => 'Unsupported message type.',
                'possible_reasons' => 'Invalid or unrecognized message type payload.',
                'possible_solutions' => 'Use supported message types: text, image, audio, video, document, template, sticker, interactive, location.',
                'client_explanation' => 'The attachment or message format is not supported by WhatsApp.',
                'client_solution' => 'Use standard supported formats: Text, Images, PDF documents, Audio, or Videos.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131052',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Media Download Failed',
                'details' => 'Unable to download the media sent by the user.',
                'possible_reasons' => 'Customer attachment expired or inaccessible on WhatsApp CDN.',
                'possible_solutions' => 'Ask customer to resend the attachment.',
                'client_explanation' => 'The customer attachment could not be downloaded.',
                'client_solution' => 'Ask the customer to send the file or image again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '131053',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Media Upload Failed',
                'details' => 'Unable to upload the media used in the message.',
                'possible_reasons' => 'Unsupported MIME type, corrupted file, or media file size exceeds WhatsApp limit.',
                'possible_solutions' => 'Ensure file size is within limits (16MB for audio/video, 100MB for docs, 5MB for images) and MIME type is valid.',
                'client_explanation' => 'The file you attached could not be uploaded to WhatsApp.',
                'client_solution' => 'Make sure the file size is under WhatsApp limits (under 16MB for audio/video, under 100MB for documents, under 5MB for images).',
                'http_status_code' => 400,
            ],
            [
                'code' => '131057',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'WABA Maintenance Mode',
                'details' => 'Business Account is in maintenance mode.',
                'possible_reasons' => 'WABA undergoing throughput upgrade or backend maintenance.',
                'possible_solutions' => 'Wait a few minutes before retrying.',
                'client_explanation' => 'WhatsApp is currently performing system maintenance on your account.',
                'client_solution' => 'Please wait a few minutes and try again.',
                'http_status_code' => 503,
            ],
            [
                'code' => '131063',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Marketing Templates Disabled on Cloud API',
                'details' => 'Your template is categorized as Marketing, but marketing templates are currently disabled for your Cloud API configuration.',
                'possible_reasons' => 'disable_marketing_messages_on_cloud_api is enabled on WABA.',
                'possible_solutions' => 'Set disable_marketing_messages_on_cloud_api to false in WhatsApp Manager.',
                'client_explanation' => 'Marketing templates are disabled in your WhatsApp settings.',
                'client_solution' => 'Turn on marketing messages in your WhatsApp Business Manager.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132000',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Variable Count Mismatch',
                'details' => 'The number of variable parameter values included in the request did not match the number of variable parameters defined in the template.',
                'possible_reasons' => 'Missing or extra parameter values passed for template body/header variables.',
                'possible_solutions' => 'Provide values for all variable parameters defined in the approved template.',
                'client_explanation' => 'Some custom variables (such as customer name or order ID) are missing.',
                'client_solution' => 'Fill in all required fields for this template before sending.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132001',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Not Found or Not Approved',
                'details' => 'The template does not exist in the specified language or the template has not been approved.',
                'possible_reasons' => 'Template name typo, incorrect language locale (e.g. en vs en_US), or template still in review.',
                'possible_solutions' => 'Verify template name, exact language code, and confirm status is APPROVED in WhatsApp Manager.',
                'client_explanation' => 'This message template is not approved yet by WhatsApp or does not exist in this language.',
                'client_solution' => 'Make sure the template is marked as "Approved" in your Templates list before sending.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132005',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Translated Text Too Long',
                'details' => 'Translated text is too long.',
                'possible_reasons' => 'Template translation exceeded component character limits.',
                'possible_solutions' => 'Shorten template content in WhatsApp Manager.',
                'client_explanation' => 'The template message text is too long.',
                'client_solution' => 'Shorten the template text in your template editor.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132007',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Violates Policy',
                'details' => 'Template content violates a WhatsApp policy.',
                'possible_reasons' => 'Template flagged for policy violation (e.g. adult content, gambling, drugs, spam).',
                'possible_solutions' => 'Review WhatsApp Template Guidelines and edit template content before resubmission.',
                'client_explanation' => 'This template was rejected by WhatsApp for violating messaging policies.',
                'client_solution' => 'Edit the template message to follow WhatsApp commercial guidelines.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132012',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Parameter Formatting Invalid',
                'details' => 'Variable parameter values formatted incorrectly.',
                'possible_reasons' => 'Parameter object structure does not match expected component type.',
                'possible_solutions' => 'Ensure parameter structure matches type (text, currency, date_time).',
                'client_explanation' => 'The information filled into the template is formatted incorrectly.',
                'client_solution' => 'Check date and number formats in the template inputs and try again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132015',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Paused Due to Low Quality',
                'details' => 'Template is paused due to low quality so it cannot be sent in a template message.',
                'possible_reasons' => 'Users frequently reported or blocked this template.',
                'possible_solutions' => 'Edit template content to improve relevance and quality; pause lifts after quality recovery.',
                'client_explanation' => 'This template is temporarily paused by WhatsApp because several customers reported it as low quality.',
                'client_solution' => 'Improve the wording of the template to make it clearer and more helpful to your customers.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132016',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Template Permanently Disabled',
                'details' => 'Template has been paused too many times due to low quality and is now permanently disabled.',
                'possible_reasons' => 'Repeated quality threshold failures.',
                'possible_solutions' => 'Create a new template with clearer, more relevant messaging.',
                'client_explanation' => 'This template has been permanently disabled by WhatsApp.',
                'client_solution' => 'Create a new template with fresh, customer-friendly messaging.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132068',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Flow Blocked',
                'details' => 'Flow is in blocked state.',
                'possible_reasons' => 'WhatsApp Flow configuration contains errors or violated policy.',
                'possible_solutions' => 'Correct and test the Flow in WhatsApp Flows Builder.',
                'client_explanation' => 'Your interactive WhatsApp Flow is blocked.',
                'client_solution' => 'Check and test your Flow in Meta WhatsApp Flows Builder.',
                'http_status_code' => 400,
            ],
            [
                'code' => '132069',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Flow Hourly Throttle',
                'details' => 'Flow is in throttled state and 10 messages using this flow were already sent in the last hour.',
                'possible_reasons' => 'Flow message rate exceeded hourly throttle limit.',
                'possible_solutions' => 'Wait for the hourly limit window to reset.',
                'client_explanation' => 'This interactive Flow reached its hourly test limit.',
                'client_solution' => 'Please wait 1 hour before sending more messages using this Flow.',
                'http_status_code' => 429,
            ],
            [
                'code' => '133000',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Deregistration Failed',
                'details' => 'A previous deregistration attempt failed.',
                'possible_reasons' => 'Phone number deregistration was interrupted.',
                'possible_solutions' => 'Deregister the number again before registering.',
                'client_explanation' => 'Disconnecting this phone number was interrupted.',
                'client_solution' => 'Try disconnecting and reconnecting the number again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '133004',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Registration Server Unavailable',
                'details' => 'Server is temporarily unavailable.',
                'possible_reasons' => 'Meta phone number registration server temporary downtime.',
                'possible_solutions' => 'Retry registration after a few minutes.',
                'client_explanation' => 'WhatsApp registration servers are temporarily busy.',
                'client_solution' => 'Please try again in a few minutes.',
                'http_status_code' => 503,
            ],
            [
                'code' => '133005',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Two-Step Verification PIN Incorrect',
                'details' => 'Two-step verification PIN incorrect.',
                'possible_reasons' => 'Entered PIN does not match the 6-digit registration PIN.',
                'possible_solutions' => 'Verify the 6-digit PIN or reset two-step verification PIN in WhatsApp Manager.',
                'client_explanation' => 'The 6-digit two-step verification security PIN is incorrect.',
                'client_solution' => 'Enter your correct 6-digit PIN, or reset it in WhatsApp Manager.',
                'http_status_code' => 400,
            ],
            [
                'code' => '133006',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Phone Number Needs Verification',
                'details' => 'Phone number needs to be verified before registering.',
                'possible_reasons' => 'SMS/Voice verification code step has not been completed.',
                'possible_solutions' => 'Request verification code via SMS/Voice and verify ownership before registration.',
                'client_explanation' => 'This phone number has not finished the SMS/Voice verification code step.',
                'client_solution' => 'Request a verification code to confirm phone number ownership.',
                'http_status_code' => 400,
            ],
            [
                'code' => '133008',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Too Many PIN Guesses',
                'details' => 'Too many two-step verification PIN guesses for this phone number.',
                'possible_reasons' => 'Exceeded allowed incorrect PIN attempts.',
                'possible_solutions' => 'Wait for the lockout cooldown period before submitting PIN again.',
                'client_explanation' => 'Too many incorrect PIN attempts were entered.',
                'client_solution' => 'Please wait a while before entering your PIN again.',
                'http_status_code' => 429,
            ],
            [
                'code' => '133009',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'PIN Entered Too Quickly',
                'details' => 'Two-step verification PIN was entered too quickly.',
                'possible_reasons' => 'Rapid automated submission.',
                'possible_solutions' => 'Wait a few seconds before retrying PIN entry.',
                'client_explanation' => 'PIN was submitted too quickly.',
                'client_solution' => 'Please wait a few seconds and try again.',
                'http_status_code' => 429,
            ],
            [
                'code' => '133010',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Phone Number Not Registered on Platform',
                'details' => 'Phone number not registered on the WhatsApp Business Platform.',
                'possible_reasons' => 'Phone number ID exists but registration endpoint was not called.',
                'possible_solutions' => 'Register the phone number with 6-digit PIN before calling messaging APIs.',
                'client_explanation' => 'This phone number is not registered on WhatsApp Business yet.',
                'client_solution' => 'Complete the phone number registration in Channels first.',
                'http_status_code' => 400,
            ],
            [
                'code' => '133015',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Phone Number Recently Deleted',
                'details' => 'The phone number you are attempting to register was recently deleted, and deletion has not yet completed.',
                'possible_reasons' => 'Deletion process is still synchronizing across Meta data centers.',
                'possible_solutions' => 'Wait 5 minutes for deletion to finish before re-registering.',
                'client_explanation' => 'This phone number was recently deleted and is still being processed by WhatsApp.',
                'client_solution' => 'Please wait 5 minutes before registering it again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '134011',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'WhatsApp Payments Terms Pending',
                'details' => 'Message failed to send because WhatsApp Payments terms of service acceptance is pending for this WhatsApp Business Account.',
                'possible_reasons' => 'WhatsApp Payments terms of service not accepted.',
                'possible_solutions' => 'Accept WhatsApp Payments terms of service in Meta Business Suite.',
                'client_explanation' => 'You need to accept WhatsApp Payment terms before sending this message.',
                'client_solution' => 'Accept the payments terms in Meta Business Suite.',
                'http_status_code' => 400,
            ],
            [
                'code' => '135000',
                'subcode' => null,
                'category' => 'Other',
                'title' => 'Unknown Request Parameter Error',
                'details' => 'Message failed to send because of an unknown error with your request parameters.',
                'possible_reasons' => 'Unrecognized payload structure or invalid parameter syntax.',
                'possible_solutions' => 'Verify endpoint request parameters against official Cloud API documentation.',
                'client_explanation' => 'Some information in your request is not recognized by WhatsApp.',
                'client_solution' => 'Check the details and submit again.',
                'http_status_code' => 400,
            ],

            // Marketing Messages API errors
            [
                'code' => '131055',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Method Not Allowed (Marketing Only)',
                'details' => 'Only marketing template messages are supported.',
                'possible_reasons' => 'Attempted to send a utility or authentication template via Marketing Messages API.',
                'possible_solutions' => 'Ensure the message template is categorized as MARKETING.',
                'client_explanation' => 'Only marketing templates can be sent using this campaign feature.',
                'client_solution' => 'Choose a template categorized as Marketing.',
                'http_status_code' => 400,
            ],
            [
                'code' => '134100',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Only Marketing Messages Supported',
                'details' => 'You\'re only able to send marketing messages on this API.',
                'possible_reasons' => 'Sent a non-marketing template to the Marketing Messages endpoint.',
                'possible_solutions' => 'Use templates with category MARKETING.',
                'client_explanation' => 'This broadcast feature only supports marketing messages.',
                'client_solution' => 'Select a Marketing template to send.',
                'http_status_code' => 400,
            ],
            [
                'code' => '134101',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Template Still Syncing',
                'details' => 'When you send a message from a template, the template syncing process can take up to 10 minutes to complete. Wait a few minutes, and then try sending your message again.',
                'possible_reasons' => 'Newly created template is undergoing Ad / Marketing infrastructure synchronization.',
                'possible_solutions' => 'Wait up to 10 minutes for Ad synchronization to complete, then retry sending.',
                'client_explanation' => 'Your new template was just created and is still syncing with WhatsApp servers.',
                'client_solution' => 'Please wait 5 to 10 minutes for sync to complete, then try sending again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '134102',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Template Unavailable for Use',
                'details' => 'Please check your eligibility status to ensure you are onboarded or contact Meta\'s customer support.',
                'possible_reasons' => 'Ad synchronization failed or WABA is not eligible for Marketing Messages API.',
                'possible_solutions' => 'Check WABA onboarding status in WhatsApp Manager or contact Meta Support.',
                'client_explanation' => 'This marketing template is temporarily unavailable.',
                'client_solution' => 'Check template status in WhatsApp Manager or select another template.',
                'http_status_code' => 500,
            ],
            [
                'code' => '132018',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Template Validation Error',
                'details' => 'There\'s an issue with the parameters in your template.',
                'possible_reasons' => 'Parameter values invalid or mismatched for the template.',
                'possible_solutions' => 'Review parameter values and re-send using a correctly configured template.',
                'client_explanation' => 'Some variables filled into this marketing template are invalid.',
                'client_solution' => 'Check your template variables and try again.',
                'http_status_code' => 400,
            ],
            [
                'code' => '1752041',
                'subcode' => null,
                'category' => 'Marketing Messages',
                'title' => 'Duplicate Onboarding Request',
                'details' => 'Duplicate Request is thrown when a client has already been invited to onboard by any partner.',
                'possible_reasons' => 'Client already received an onboarding invite from another partner.',
                'possible_solutions' => 'No further action required; all eligible WABAs are onboarded automatically.',
                'client_explanation' => 'This onboarding request was already sent previously.',
                'client_solution' => 'No action needed; your account is automatically included.',
                'http_status_code' => 400,
            ],
        ];

        foreach ($codes as $item) {
            WhatsAppErrorCode::updateOrCreate(
                [
                    'code' => $item['code'],
                    'subcode' => $item['subcode'],
                ],
                $item
            );
        }
    }
}
